# Generated by Django 2.0.6 on 2018-06-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ebooks',
            field=models.ManyToManyField(null=True, to='products.Product'),
        ),
    ]
