# Generated by Django 2.0.6 on 2018-06-06 06:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_userstripe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userStripe',
            new_name='StripeAccount',
        ),
    ]
