# Generated by Django 2.0.6 on 2018-06-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180606_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='StripeAccount',
        ),
    ]
